import http from 'node:http';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { DatabaseSync } from 'node:sqlite';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const dataDir = path.join(__dirname, 'data');
fs.mkdirSync(dataDir, { recursive: true });
const db = new DatabaseSync(path.join(dataDir, 'fieldops.sqlite'));
const PORT = Number(process.env.PORT || 8080);
const HOST = process.env.HOST || '0.0.0.0';
const JWT_SECRET = process.env.JWT_SECRET || 'CHANGE_THIS_JWT_SECRET_IN_PRODUCTION';
const ADMIN_EMAIL = (process.env.ADMIN_EMAIL || 'admin@fieldops.local').trim().toLowerCase();
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || 'ChangeMe123!';
const DEMO_DATA = process.env.FIELDOPS_DEMO_DATA === 'true';

if (JWT_SECRET.length < 32) console.warn('WARNING: JWT_SECRET should be at least 32 characters in production.');

const nowIso = () => new Date().toISOString();
const id = prefix => `${prefix}_${crypto.randomUUID()}`;
const json = (res, status, payload) => { const body=JSON.stringify(payload); res.writeHead(status, {'Content-Type':'application/json; charset=utf-8','Content-Length':Buffer.byteLength(body),'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET,POST,PATCH,DELETE,OPTIONS'}); res.end(body); };
const error = (res,status,message) => json(res,status,{error:message});
const hashPassword = (password, salt=crypto.randomBytes(16).toString('hex')) => ({salt,hash:crypto.scryptSync(password,salt,64).toString('hex')});
const verifyPassword = (password,salt,expected) => { try { const a=Buffer.from(hashPassword(password,salt).hash,'hex'); const b=Buffer.from(expected,'hex'); return a.length===b.length&&crypto.timingSafeEqual(a,b); } catch { return false; } };
const b64 = v => Buffer.from(v).toString('base64url');
function signToken(payload){ const h=b64(JSON.stringify({alg:'HS256',typ:'JWT'})); const p=b64(JSON.stringify(payload)); const s=crypto.createHmac('sha256',JWT_SECRET).update(`${h}.${p}`).digest('base64url'); return `${h}.${p}.${s}`; }
function verifyToken(token){ try { const [h,p,s]=token.split('.'); if(!h||!p||!s)return null; const e=crypto.createHmac('sha256',JWT_SECRET).update(`${h}.${p}`).digest('base64url'); if(s.length!==e.length||!crypto.timingSafeEqual(Buffer.from(s),Buffer.from(e)))return null; const payload=JSON.parse(Buffer.from(p,'base64url').toString()); return payload.exp>Date.now()/1000?payload:null; } catch { return null; } }
async function readJson(req){ return await new Promise((resolve,reject)=>{let data='';req.on('data',c=>{data+=c;if(Buffer.byteLength(data)>5*1024*1024)req.destroy(new Error('Request terlalu besar.'));});req.on('end',()=>{try{resolve(data?JSON.parse(data):{});}catch{reject(new Error('JSON tidak valid.'));}});req.on('error',reject);}); }
function userFromRequest(req){ const h=req.headers.authorization||''; return h.startsWith('Bearer ')?verifyToken(h.slice(7)):null; }
function requireAuth(req,res,roles=[]){ const u=userFromRequest(req); if(!u){error(res,401,'Sesi tidak valid atau sudah kedaluwarsa.');return null;} if(roles.length&&!roles.includes(u.role)){error(res,403,'Anda tidak memiliki akses untuk tindakan ini.');return null;} return u; }
function requireBodyString(body,key,max=500){ const v=String(body?.[key]??'').trim(); if(!v||v.length>max)throw new Error(`${key} wajib diisi.`); return v; }

// Fresh, tenant-aware schema. Production data is never seeded unless FIELDOPS_DEMO_DATA=true.
db.exec(`
PRAGMA foreign_keys=ON;
PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS companies(id TEXT PRIMARY KEY,name TEXT NOT NULL,industry TEXT NOT NULL,phone TEXT NOT NULL,email TEXT NOT NULL,address TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,email TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,password_salt TEXT NOT NULL,name TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('ADMIN','DISPATCHER','TECHNICIAN','MANAGER')),active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS customers(id TEXT PRIMARY KEY,company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,company_name TEXT NOT NULL,industry TEXT NOT NULL,contact_person TEXT NOT NULL,phone TEXT NOT NULL,email TEXT NOT NULL,address TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sites(id TEXT PRIMARY KEY,customer_id TEXT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,site_name TEXT NOT NULL,address TEXT NOT NULL,city TEXT NOT NULL,contact_person TEXT NOT NULL,phone TEXT NOT NULL,latitude REAL NOT NULL,longitude REAL NOT NULL);
CREATE TABLE IF NOT EXISTS assets(id TEXT PRIMARY KEY,site_id TEXT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,asset_code TEXT NOT NULL UNIQUE,name TEXT NOT NULL,brand TEXT NOT NULL,model TEXT NOT NULL,serial_number TEXT NOT NULL,category TEXT NOT NULL,installation_date TEXT NOT NULL,status TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS work_orders(id TEXT PRIMARY KEY,company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,title TEXT NOT NULL,customer TEXT NOT NULL,location TEXT NOT NULL,date TEXT NOT NULL,time TEXT NOT NULL,status TEXT NOT NULL,priority TEXT NOT NULL,asset_id TEXT REFERENCES assets(id),assigned_to TEXT REFERENCES users(id),created_by TEXT REFERENCES users(id),updated_at TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS work_order_notes(id TEXT PRIMARY KEY,work_order_id TEXT NOT NULL REFERENCES work_orders(id) ON DELETE CASCADE,note TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT REFERENCES users(id));
CREATE TABLE IF NOT EXISTS work_order_photos(id TEXT PRIMARY KEY,work_order_id TEXT NOT NULL REFERENCES work_orders(id) ON DELETE CASCADE,title TEXT NOT NULL,file_path TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT REFERENCES users(id));
CREATE TABLE IF NOT EXISTS location_evidence(work_order_id TEXT PRIMARY KEY REFERENCES work_orders(id) ON DELETE CASCADE,latitude REAL NOT NULL,longitude REAL NOT NULL,captured_at TEXT NOT NULL,captured_by TEXT REFERENCES users(id));
CREATE TABLE IF NOT EXISTS activity_history(id TEXT PRIMARY KEY,company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,work_order_id TEXT NOT NULL REFERENCES work_orders(id) ON DELETE CASCADE,title TEXT NOT NULL,description TEXT NOT NULL,time TEXT NOT NULL,type TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT REFERENCES users(id));
CREATE TABLE IF NOT EXISTS notifications(id TEXT PRIMARY KEY,title TEXT NOT NULL,description TEXT NOT NULL,time TEXT NOT NULL,type TEXT NOT NULL,is_read INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,user_id TEXT REFERENCES users(id),company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE);
`);

function ensureBootstrap(){
  let company=db.prepare('SELECT * FROM companies ORDER BY created_at LIMIT 1').get();
  if(!company){ company={id:'company_default',name:'FieldOps Operations',industry:'Field Service',phone:'',email:ADMIN_EMAIL,address:'',created_at:nowIso()}; db.prepare('INSERT INTO companies VALUES (?,?,?,?,?,?,?)').run(company.id,company.name,company.industry,company.phone,company.email,company.address,company.created_at); }
  const admin=db.prepare('SELECT id FROM users WHERE email=?').get(ADMIN_EMAIL);
  if(!admin){ const p=hashPassword(ADMIN_PASSWORD); db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,?,?,?)').run('user_admin',company.id,ADMIN_EMAIL,p.hash,p.salt,'FieldOps Administrator','ADMIN',1,nowIso()); }
  if(!DEMO_DATA)return;
  if(db.prepare('SELECT COUNT(*) c FROM customers WHERE company_id=?').get(company.id).c>0)return;
  const c='customer_demo_001'; db.prepare('INSERT INTO customers VALUES (?,?,?,?,?,?,?,?,?)').run(c,company.id,'PT ABC Manufacturing','Manufacturing','Budi Santoso','021-5550001','contact@abc.co.id','Jl. Sudirman No. 123, Jakarta',nowIso());
  db.prepare('INSERT INTO sites VALUES (?,?,?,?,?,?,?,?,?)').run('site_demo_001',c,'Gedung Head Office Jakarta','Jl. Sudirman No. 123, Jakarta','Jakarta','Budi Santoso','081234567890',-6.2,106.816666);
  db.prepare('INSERT INTO assets VALUES (?,?,?,?,?,?,?,?,?,?)').run('asset_demo_001','site_demo_001','AC-JKT-001','Air Conditioner Ruang Server','Daikin','FTKC35','SN-AC-001','HVAC','2024-01-15','ACTIVE');
}
ensureBootstrap();

const transitions={PENDING:new Set(['ACCEPTED','CANCELLED']),ACCEPTED:new Set(['IN_PROGRESS','CANCELLED']),IN_PROGRESS:new Set(['COMPLETED','CANCELLED']),COMPLETED:new Set(),CANCELLED:new Set()};
function mapUser(r){return{id:r.id,email:r.email,name:r.name,role:r.role,active:Boolean(r.active),companyId:r.company_id};}
function mapWo(r){return{id:r.id,title:r.title,customer:r.customer,location:r.location,date:r.date,time:r.time,status:r.status,priority:r.priority,assetId:r.asset_id??null,assignedTo:r.assigned_to??null,createdBy:r.created_by??null};}
function getCustomer(companyId,cid){ const c=db.prepare('SELECT * FROM customers WHERE id=? AND company_id=?').get(cid,companyId); if(!c)return null; const sites=db.prepare('SELECT * FROM sites WHERE customer_id=? ORDER BY site_name').all(cid).map(s=>({...{id:s.id,customerId:s.customer_id,siteName:s.site_name,address:s.address,city:s.city,contactPerson:s.contact_person,phone:s.phone,latitude:s.latitude,longitude:s.longitude},assets:db.prepare('SELECT * FROM assets WHERE site_id=? ORDER BY asset_code').all(s.id).map(a=>({id:a.id,siteId:a.site_id,assetCode:a.asset_code,name:a.name,brand:a.brand,model:a.model,serialNumber:a.serial_number,category:a.category,installationDate:a.installation_date,status:a.status}))})); return{id:c.id,companyId:c.company_id,companyName:c.company_name,industry:c.industry,contactPerson:c.contact_person,phone:c.phone,email:c.email,address:c.address,sites}; }
function canSeeWo(u,r){return u.role==='TECHNICIAN'?r.assigned_to===u.sub:r.company_id===u.companyId;}
function addActivity(companyId,woId,title,description,type,createdBy){const t=new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'});db.prepare('INSERT INTO activity_history VALUES (?,?,?,?,?,?,?,?,?)').run(id('activity'),companyId,woId,title,description,t,type,nowIso(),createdBy);}
function addNotification(companyId,userId,title,description,type){const t=new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'});db.prepare('INSERT INTO notifications VALUES (?,?,?,?,?,?,?,?,?)').run(id('notification'),title,description,t,type,0,nowIso(),userId,companyId);}

async function handle(req,res){
  if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET,POST,PATCH,DELETE,OPTIONS'});return res.end();}
  const url=new URL(req.url,`http://${req.headers.host||'localhost'}`); const parts=url.pathname.replace(/^\/api\/?/,'').split('/').filter(Boolean);
  try{
    if(req.method==='GET'&&url.pathname==='/api/health')return json(res,200,{status:'ok',service:'FieldOps Backend',time:nowIso()});
    if(req.method==='POST'&&parts.join('/')==='auth/login'){
      const b=await readJson(req),email=String(b.email||'').trim().toLowerCase(),password=String(b.password||'');
      const u=db.prepare('SELECT * FROM users WHERE lower(email)=? AND active=1').get(email); if(!u||!verifyPassword(password,u.password_salt,u.password_hash))return error(res,401,'Email atau password salah.');
      return json(res,200,{token:signToken({sub:u.id,email:u.email,name:u.name,role:u.role,companyId:u.company_id,exp:Math.floor(Date.now()/1000)+60*60*12}),user:mapUser(u)});
    }
    const u=requireAuth(req,res); if(!u)return;
    if(req.method==='GET'&&parts.join('/')==='me'){const r=db.prepare('SELECT * FROM users WHERE id=? AND active=1').get(u.sub);if(!r)return error(res,401,'Akun tidak aktif.');return json(res,200,mapUser(r));}
    if(req.method==='GET'&&parts.join('/')==='dashboard/summary'){
      const rows=db.prepare('SELECT status,COUNT(*) c FROM work_orders WHERE company_id=? GROUP BY status').all(u.companyId);const m={PENDING:0,ACCEPTED:0,IN_PROGRESS:0,COMPLETED:0,CANCELLED:0};for(const r of rows)m[r.status]=r.c;return json(res,200,{total:Object.values(m).reduce((a,b)=>a+b,0),...m});
    }
    if(req.method==='GET'&&parts[0]==='users'&&parts.length===1){if(!['ADMIN','MANAGER','DISPATCHER'].includes(u.role))return error(res,403,'Akses ditolak.');return json(res,200,db.prepare('SELECT * FROM users WHERE company_id=? ORDER BY name').all(u.companyId).map(mapUser));}
    if(req.method==='POST'&&parts[0]==='users'&&parts.length===1){if(u.role!=='ADMIN')return error(res,403,'Hanya Admin yang dapat membuat user.');const b=await readJson(req),email=requireBodyString(b,'email',200).toLowerCase(),name=requireBodyString(b,'name',120),role=requireBodyString(b,'role',20).toUpperCase(),password=requireBodyString(b,'password',200);if(!['ADMIN','DISPATCHER','TECHNICIAN','MANAGER'].includes(role))return error(res,400,'Role tidak valid.');if(password.length<8)return error(res,400,'Password minimal 8 karakter.');if(db.prepare('SELECT id FROM users WHERE email=?').get(email))return error(res,409,'Email sudah digunakan.');const p=hashPassword(password),r={id:id('user'),company_id:u.companyId,email,password_hash:p.hash,password_salt:p.salt,name,role,active:1,created_at:nowIso()};db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,?,?,?)').run(r.id,r.company_id,r.email,r.password_hash,r.password_salt,r.name,r.role,r.active,r.created_at);return json(res,201,mapUser(r));}
    if(req.method==='PATCH'&&parts[0]==='users'&&parts.length===2){if(u.role!=='ADMIN')return error(res,403,'Hanya Admin yang dapat mengubah user.');const target=db.prepare('SELECT * FROM users WHERE id=? AND company_id=?').get(parts[1],u.companyId);if(!target)return error(res,404,'User tidak ditemukan.');const b=await readJson(req);const name=b.name===undefined?target.name:requireBodyString(b,'name',120);const role=b.role===undefined?target.role:String(b.role).toUpperCase();const active=b.active===undefined?Boolean(target.active):Boolean(b.active);if(!['ADMIN','DISPATCHER','TECHNICIAN','MANAGER'].includes(role))return error(res,400,'Role tidak valid.');db.prepare('UPDATE users SET name=?,role=?,active=? WHERE id=?').run(name,role,active?1:0,target.id);return json(res,200,mapUser(db.prepare('SELECT * FROM users WHERE id=?').get(target.id)));}
    if(req.method==='GET'&&parts[0]==='work-orders'&&parts.length===1){const rows=db.prepare('SELECT * FROM work_orders WHERE company_id=? ORDER BY date,time,id').all(u.companyId).filter(r=>canSeeWo(u,r));return json(res,200,rows.map(mapWo));}
    if(req.method==='GET'&&parts[0]==='work-orders'&&parts.length===2){const r=db.prepare('SELECT * FROM work_orders WHERE id=? AND company_id=?').get(parts[1],u.companyId);if(!r||!canSeeWo(u,r))return error(res,404,'Work Order tidak ditemukan.');return json(res,200,mapWo(r));}
    if(req.method==='POST'&&parts[0]==='work-orders'&&parts.length===1){if(!['ADMIN','DISPATCHER'].includes(u.role))return error(res,403,'Hanya Admin/Dispatcher yang dapat membuat Work Order.');const b=await readJson(req);const title=requireBodyString(b,'title',200),customer=requireBodyString(b,'customer',200),location=requireBodyString(b,'location',300),date=requireBodyString(b,'date',20),time=requireBodyString(b,'time',20),priority=(String(b.priority||'MEDIUM').toUpperCase());if(!['LOW','MEDIUM','HIGH'].includes(priority))return error(res,400,'Prioritas tidak valid.');const ass=b.assignedTo?String(b.assignedTo):null;if(ass){const tech=db.prepare("SELECT id FROM users WHERE id=? AND company_id=? AND role='TECHNICIAN' AND active=1").get(ass,u.companyId);if(!tech)return error(res,400,'Teknisi tidak valid.');}const r={id:id('WO'),company_id:u.companyId,title,customer,location,date,time,status:'PENDING',priority,asset_id:b.assetId?String(b.assetId):null,assigned_to:ass,created_by:u.sub,updated_at:nowIso(),created_at:nowIso()};db.prepare('INSERT INTO work_orders VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(...Object.values(r));addActivity(u.companyId,r.id,'Work Order Dibuat',`${r.id} dibuat oleh ${u.name}`,'STATUS',u.sub);if(ass)addNotification(u.companyId,ass,'Work Order Baru',`${r.id} ditugaskan kepada Anda.`,'STATUS');return json(res,201,mapWo(r));}
    if(req.method==='PATCH'&&parts[0]==='work-orders'&&parts.length===3&&parts[2]==='status'){const b=await readJson(req),next=String(b.status||'').toUpperCase(),r=db.prepare('SELECT * FROM work_orders WHERE id=? AND company_id=?').get(parts[1],u.companyId);if(!r||!canSeeWo(u,r))return error(res,404,'Work Order tidak ditemukan.');if(!transitions[r.status]?.has(next))return error(res,409,`Perubahan status ${r.status} ke ${next} tidak diizinkan.`);if(u.role==='TECHNICIAN'&&next==='CANCELLED')return error(res,403,'Teknisi tidak dapat membatalkan Work Order.');db.prepare('UPDATE work_orders SET status=?,updated_at=? WHERE id=?').run(next,nowIso(),r.id);addActivity(u.companyId,r.id,'Status Work Order Diperbarui',`${r.id} berubah dari ${r.status} menjadi ${next}`,'STATUS',u.sub);addNotification(u.companyId,r.assigned_to||u.sub,'Status Work Order Diperbarui',`${r.id} sekarang ${next}`,'STATUS');return json(res,200,mapWo(db.prepare('SELECT * FROM work_orders WHERE id=?').get(r.id)));}
    if(req.method==='PATCH'&&parts[0]==='work-orders'&&parts.length===3&&parts[2]==='assignment'){if(!['ADMIN','DISPATCHER'].includes(u.role))return error(res,403,'Hanya Admin/Dispatcher yang dapat melakukan assignment.');const b=await readJson(req),r=db.prepare('SELECT * FROM work_orders WHERE id=? AND company_id=?').get(parts[1],u.companyId);if(!r)return error(res,404,'Work Order tidak ditemukan.');const ass=b.assignedTo?String(b.assignedTo):null;if(ass&&!db.prepare("SELECT id FROM users WHERE id=? AND company_id=? AND role='TECHNICIAN' AND active=1").get(ass,u.companyId))return error(res,400,'Teknisi tidak valid.');db.prepare('UPDATE work_orders SET assigned_to=?,updated_at=? WHERE id=?').run(ass,nowIso(),r.id);addActivity(u.companyId,r.id,'Assignment Diperbarui',ass?`Ditugaskan kepada ${db.prepare('SELECT name FROM users WHERE id=?').get(ass).name}.`:'Assignment dilepas.','STATUS',u.sub);if(ass)addNotification(u.companyId,ass,'Work Order Ditugaskan',`${r.id} masuk ke daftar pekerjaan Anda.`,'STATUS');return json(res,200,mapWo(db.prepare('SELECT * FROM work_orders WHERE id=?').get(r.id)));}
    if(req.method==='GET'&&parts[0]==='customers'&&parts.length===1)return json(res,200,db.prepare('SELECT id FROM customers WHERE company_id=? ORDER BY company_name').all(u.companyId).map(r=>getCustomer(u.companyId,r.id)));
    if(req.method==='GET'&&parts[0]==='customers'&&parts.length===2){const c=getCustomer(u.companyId,parts[1]);if(!c)return error(res,404,'Customer tidak ditemukan.');return json(res,200,c);}
    if(req.method==='POST'&&parts[0]==='customers'&&parts.length===1){if(!['ADMIN','DISPATCHER'].includes(u.role))return error(res,403,'Hanya Admin/Dispatcher yang dapat membuat customer.');const b=await readJson(req);const r={id:id('customer'),company_id:u.companyId,company_name:requireBodyString(b,'companyName',200),industry:requireBodyString(b,'industry',120),contact_person:requireBodyString(b,'contactPerson',120),phone:requireBodyString(b,'phone',40),email:requireBodyString(b,'email',200),address:requireBodyString(b,'address',300),created_at:nowIso()};db.prepare('INSERT INTO customers VALUES (?,?,?,?,?,?,?,?,?)').run(...Object.values(r));return json(res,201,getCustomer(u.companyId,r.id));}
    if(req.method==='PATCH'&&parts[0]==='customers'&&parts.length===2){if(!['ADMIN','DISPATCHER'].includes(u.role))return error(res,403,'Akses ditolak.');const old=db.prepare('SELECT * FROM customers WHERE id=? AND company_id=?').get(parts[1],u.companyId);if(!old)return error(res,404,'Customer tidak ditemukan.');const b=await readJson(req);const r={company_name:b.companyName===undefined?old.company_name:requireBodyString(b,'companyName',200),industry:b.industry===undefined?old.industry:requireBodyString(b,'industry',120),contact_person:b.contactPerson===undefined?old.contact_person:requireBodyString(b,'contactPerson',120),phone:b.phone===undefined?old.phone:requireBodyString(b,'phone',40),email:b.email===undefined?old.email:requireBodyString(b,'email',200),address:b.address===undefined?old.address:requireBodyString(b,'address',300)};db.prepare('UPDATE customers SET company_name=?,industry=?,contact_person=?,phone=?,email=?,address=? WHERE id=? AND company_id=?').run(r.company_name,r.industry,r.contact_person,r.phone,r.email,r.address,old.id,u.companyId);return json(res,200,getCustomer(u.companyId,old.id));}
    if(req.method==='DELETE'&&parts[0]==='customers'&&parts.length===2){if(u.role!=='ADMIN')return error(res,403,'Hanya Admin yang dapat menghapus customer.');const r=db.prepare('SELECT id FROM customers WHERE id=? AND company_id=?').get(parts[1],u.companyId);if(!r)return error(res,404,'Customer tidak ditemukan.');db.prepare('DELETE FROM customers WHERE id=?').run(r.id);return json(res,200,{success:true});}
    if(req.method==='GET'&&parts.join('/')==='activity-history'){const rows=db.prepare('SELECT * FROM activity_history WHERE company_id=? ORDER BY created_at DESC').all(u.companyId).filter(r=>u.role!=='TECHNICIAN'||db.prepare('SELECT assigned_to FROM work_orders WHERE id=?').get(r.work_order_id)?.assigned_to===u.sub);return json(res,200,rows.map(r=>({id:r.id,workOrderId:r.work_order_id,title:r.title,description:r.description,time:r.time,type:r.type})));}
    if(req.method==='GET'&&parts.join('/')==='notifications'){const rows=db.prepare('SELECT * FROM notifications WHERE company_id=? AND (user_id=? OR user_id IS NULL) ORDER BY created_at DESC').all(u.companyId,u.sub);return json(res,200,rows.map(r=>({id:r.id,title:r.title,description:r.description,time:r.time,type:r.type,isRead:Boolean(r.is_read)})));}
    if(req.method==='PATCH'&&parts[0]==='notifications'&&parts.length===3&&parts[2]==='read'){db.prepare('UPDATE notifications SET is_read=1 WHERE id=? AND company_id=? AND (user_id=? OR user_id IS NULL)').run(parts[1],u.companyId,u.sub);return json(res,200,{success:true});}
    if(req.method==='POST'&&parts[0]==='work-orders'&&parts.length===3&&parts[2]==='notes'){const r=db.prepare('SELECT id FROM work_orders WHERE id=? AND company_id=?').get(parts[1],u.companyId);if(!r)return error(res,404,'Work Order tidak ditemukan.');if(u.role==='TECHNICIAN' && db.prepare('SELECT assigned_to FROM work_orders WHERE id=?').get(r.id)?.assigned_to !== u.sub)return error(res,403,'Akses ditolak.');const b=await readJson(req),note=requireBodyString(b,'note',5000);const nid=id('note'),t=nowIso();db.prepare('INSERT INTO work_order_notes VALUES (?,?,?,?,?)').run(nid,r.id,note,t,u.sub);addActivity(u.companyId,r.id,'Catatan Ditambahkan',`${u.name} menambahkan catatan.`,'NOTE',u.sub);return json(res,201,{id:nid,workOrderId:r.id,note,createdAt:t});}
    if(req.method==='GET'&&parts[0]==='work-orders'&&parts.length===3&&parts[2]==='notes'){const r=db.prepare('SELECT * FROM work_orders WHERE id=? AND company_id=?').get(parts[1],u.companyId);if(!r||!canSeeWo(u,r))return error(res,404,'Work Order tidak ditemukan.');return json(res,200,db.prepare('SELECT * FROM work_order_notes WHERE work_order_id=? ORDER BY created_at').all(r.id).map(x=>({id:x.id,workOrderId:x.work_order_id,note:x.note,createdAt:x.created_at})));}
    if(req.method==='POST'&&parts[0]==='work-orders'&&parts.length===3&&parts[2]==='location'){const r=db.prepare('SELECT * FROM work_orders WHERE id=? AND company_id=?').get(parts[1],u.companyId);if(!r||!canSeeWo(u,r))return error(res,404,'Work Order tidak ditemukan.');const b=await readJson(req),lat=Number(b.latitude),lon=Number(b.longitude);if(!Number.isFinite(lat)||lat<-90||lat>90||!Number.isFinite(lon)||lon<-180||lon>180)return error(res,400,'Koordinat tidak valid.');const t=nowIso();db.prepare('INSERT INTO location_evidence VALUES (?,?,?,?,?) ON CONFLICT(work_order_id) DO UPDATE SET latitude=excluded.latitude,longitude=excluded.longitude,captured_at=excluded.captured_at,captured_by=excluded.captured_by').run(r.id,lat,lon,t,u.sub);addActivity(u.companyId,r.id,'Lokasi GPS Disimpan',`${u.name} menyimpan bukti lokasi.`,'LOCATION',u.sub);return json(res,201,{workOrderId:r.id,latitude:lat,longitude:lon,capturedAt:t});}
    if(req.method==='GET'&&parts[0]==='work-orders'&&parts.length===3&&parts[2]==='location'){const r=db.prepare('SELECT * FROM work_orders WHERE id=? AND company_id=?').get(parts[1],u.companyId);if(!r||!canSeeWo(u,r))return error(res,404,'Work Order tidak ditemukan.');const x=db.prepare('SELECT * FROM location_evidence WHERE work_order_id=?').get(r.id);return json(res,200,x?{workOrderId:x.work_order_id,latitude:x.latitude,longitude:x.longitude,capturedAt:x.captured_at}:null);}
    return error(res,404,'Endpoint tidak ditemukan.');
  }catch(e){console.error(e);return error(res,400,e.message||'Permintaan tidak dapat diproses.');}
}
http.createServer(handle).listen(PORT,HOST,()=>console.log(`FieldOps Backend running at http://${HOST}:${PORT}`));
process.on('SIGINT',()=>{db.close();process.exit(0);});process.on('SIGTERM',()=>{db.close();process.exit(0);});
